### ISSUE TITLE
`awaits-parent` label after approving or state in project board

### ISSUE THREAD

**Issue by klaasnicolaas** [home-assistant/probot-home-assistant#22]
Is it possible that the `awaits-parent` label can be added to a PR if:
- We approve a doc PR but the parent PR has not merged yet? and it has the target branch `next`.
- Or when a PR in the Github project board enters the *awaits-parent PR* column.

Whether this is also ideal or not, I don't know but would like to throw the ball for ideas 😉

**Comment by balloob** [comment]
The `has-parent` label is kinda "wonky" at this moment, because it is triggered if either the HA PR points at the docs PR or if the docs PR points at the HA PR.

This one is easy with our current setup if the docs PR points at the HA PR.

On approve: 
- if we find a link to a HA PR
- check status
- if it's open
- attach `awaits-parents`

**Comment by klaasnicolaas** [comment]
After a merge, I think probot should also remove the `awaits-parent` label

**Comment by ludeeus** [comment]
With https://github.com/home-assistant/service-hub/pull/26 we are moving the source of the bot, if this change is still wanted please move the issue to that repository.
If not, please close it 👍

**Comment by klaasnicolaas** [comment]
I think we can close this issue.

It might still be useful if the label is added when the pull request state on the Github project board is adjusted, but it is unknown to me whether that is possible and whether this action is still desirable.
